#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Change snapserver source to Spotify only if no custom configuration is mounted
if ! [ -e '/config/snapserver.conf' ]; then
  if ! [ -d '/config' ]; then
    mkdir /config
  fi

  cp /etc/snapserver.conf /config/snapserver.conf

  credentials=""
  if [[ -n "${USERNAME:-}" ]] && [[ -n "${PASSWORD:-}" ]]; then
    credentials="\&username=${USERNAME}\&password=${PASSWORD}"
  elif [[ -n "${CACHE:-}" ]]; then
    credentials="\&cache=${CACHE}"
  fi
  sed -i "s,^source = .*,source = librespot:///librespot?name=Spotify\&devicename=${DEVICE_NAME:-Snapcast}\&bitrate=320\&volume=100${credentials}," /config/snapserver.conf
  sed -i "s,^doc_root = .*,doc_root = /usr/share/snapweb," /config/snapserver.conf
fi

if [[ -z ${LSIO_NON_ROOT_USER} ]]; then
    lsiown -R abc:abc \
        /config

    if grep -qe ' /data ' /proc/mounts; then
        if [[ "$(stat -c '%U' /data)" != "abc" ]]; then
            lsiown abc:abc /data
        fi
    fi
fi